### ISSUE TITLE
No workflow for only SMS

### ISSUE THREAD

**Issue by anmol5varma** [Nexmo/nexmo-java-code-snippets#65]
https://developer.nexmo.com/verify/guides/workflows-and-events
Workflow 6 is absent from `VerifyRequest.Workflow` Class. How do I implement that using nexmo java sdk?

**Comment by lornajane** [comment]
This is a duplicate of https://github.com/Nexmo/nexmo-java/issues/275 and workflow 6 can now be added since release 5.2.1 of the Java lib.
